name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Copy .env.example to .env
        run: cp ./INKOSTEL/.env ./INKOSTEL/.env.backup

      - name: Update .env for MySQL
        run: |
          echo "DB_CONNECTION=mysql" >> ./INKOSTEL/.env
          echo "DB_HOST=127.0.0.1" >> ./INKOSTEL/.env
          echo "DB_PORT=3306" >> ./INKOSTEL/.env
          echo "DB_DATABASE=testing" >> ./INKOSTEL/.env
          echo "DB_USERNAME=user" >> ./INKOSTEL/.env
          echo "DB_PASSWORD=password" >> ./INKOSTEL/.env

      - name: Run Composer
        run: composer install --no-interaction
        working-directory: ./INKOSTEL

      - name: Run migrations
        run: php artisan migrate --force
        working-directory: ./INKOSTEL

      - name: Run tests
        run: php artisan test
        working-directory: ./INKOSTEL
